### ISSUE TITLE
Funding Request: For a new faucet that works with user verification through telegram

### ISSUE THREAD

**Issue by merlox** [pk910/holesky-fundingvault#1]
### Project Name

Big Holesky Faucet

### Whats the link to your project?

https://bigoer

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

Initially we want to start with 1k a month and ramp up to more as needed

### What do you need these funds for?

I run bigoerlifaucet.com and I'm gonna create a free-only faucet for holesky. The infrastructure is there and I know how to grow communities in that regard so people have access to these faucets. The goal is to provide users with testnet eth with telegram verification so they prove they are real people.

### Wallet Address

0x063958deEC541E129711E531EbB9C7a724e2690b

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Can you please fix the link to your faucet site?
