### ISSUE TITLE
Funding Request: CROSSVALUE Chain

### ISSUE THREAD

**Issue by ngapw** [pk910/holesky-fundingvault#6]
### Project Name

CROSSVALUE Chain

### Whats the link to your project?

https://cross.technology

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

10.000 holETH

### What do you need these funds for?

We needed holETH for testing (users faucet), liquidity, and a bridge between CROSSValue and Ethereum.

### Wallet Address

0x1010DAd62a07F84182672Dab2E0335649d097eF2

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @ngapw,
Thanks for your request.

As your github profile is private, I can't really see if you're a linked to cross.technology.
Can you please put your wallet address into a TXT DNS record on your domain or 
alternatively put your wallet address into a txt file and make it reachable via http(s) on your domain?
That way we can quickly verify its a legit request :)

Besides of that I'd send you a initial 10k, then you can set up everything from your side.
If you want to provide some kind of faucet for your users or need an ongoing funding for other reasons we can do so later on.
