### ISSUE TITLE
Funding Request: Webrunners (https://www.wrfaucet.xyz/)

### ISSUE THREAD

**Issue by sich514** [pk910/holesky-fundingvault#9]
### Project Name

wrfaucet

### Whats the link to your project?

https://www.wrfaucet.xyz/

### Is this a one-time request or do you need an ongoing funding?

Ongoing Funding (monthly)

### What amount of funds do you need?

up to 2000 per month

### What do you need these funds for?

Hello
We made a simple faucet, without unnecessary information and page overload, for people who want to participate in the testnets (especially newbies to crypto) of various projects in Holesky and receive a fixed amount of ether. 
Daily limit for wallet is 0.5 ETH/day.(Now it's 0.1)
And a total daily limit of faucet is 100 ETH.
We have installed a captcha on the site, but in the event of a sybil raid, we have prepared verification modules via Twitter/Telegram.

### Wallet Address

0x09a1cB394C9Ba4b92B294De9E25Fe8e2352F5CF9

### Code of Conduct

- [X] I agree that I will not sell testnet funds for money in any way.
- [X] I agree that I will not hoard testnet funds with no actual need.

**Comment by pk910** [comment]
Heya @sich514,

Thanks for your efforts in setting up a holesky faucet. 
I think you'll need to add additional protections via twitter/tg pretty soon.
The captcha verification can be played too easily by bots...

But I'm happy to give it a try as you seem to have proper limits implemented to avoid attacks.

For verification of your request, could you please take a moment to add your wallet address into a TXT DNS record on your domain? Alternatively, you could place your wallet address into a .txt file and make it accessible via http(s) on your domain and share the link here.

That way we can quickly verify that faucet belongs to you :)

**Comment by sich514** [comment]
Thanks for the answer !
We have updated the TXT DNS record, it took a little while for it to get indexed
You can check here:
https://www.whatsmydns.net/#TXT/wrfaucet.xyz

I have a request: we still decided to make a clean wallet, because it has a transaction history, and I wouldn’t really like it to be public. It would be nice to replace it with this one:
0x68f1cbf2f9879A41c53b79666ab8A95cDD2A5616

**Comment by pk910** [comment]
Thx, you should be able to claim 2k HolETH per month from [holesky-fundingvault.vercel.app](https://holesky-fundingvault.vercel.app/) now.

As faucet dev you'd probably like to automate that process a bit to avoid clicking through a UI every month.
You can do that request programmatically by calling one of the claim functions on the vault contract from the authorized wallet.
The abi is available in this repo :)

**Comment by sich514** [comment]
Thank you , appreciate it!
